services:
  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - PERSISTENCE=1
    volumes:
      - localstack-data:/var/lib/localstack

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  jaeger:
    image: jaegertracing/all-in-one:1.58
    ports:
      - "16686:16686" # UI
      - "4318:4318"   # OTLP HTTP receiver

volumes:
  localstack-data:
  redis-data:
